# Generated by Django 4.2.30 on 2026-08-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('multiplicador', models.DecimalField(decimal_places=3, default=1, max_digits=6, verbose_name='Multiplicador')),
                ('tiene_canal_feria', models.BooleanField(default=False, verbose_name='Tiene canal Feria del Hogar')),
                ('multiplicador_feria', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Multiplicador Feria del Hogar')),
            ],
            options={
                'verbose_name': 'Categoría de Lista de Precios',
                'verbose_name_plural': 'Categorías de Lista de Precios',
                'db_table': 'listaprecios_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Grupo de Tela',
                'verbose_name_plural': 'Grupos de Tela',
                'db_table': 'listaprecios_grupo_tela',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('fotos', models.JSONField(blank=True, default=list, verbose_name='Fotos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='listaprecios.categorialista')),
            ],
            options={
                'verbose_name': 'Línea de Producto',
                'verbose_name_plural': 'Líneas de Producto',
                'db_table': 'listaprecios_linea_producto',
                'ordering': ['categoria__orden', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('costo_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo base')),
                ('metraje_tela', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Metraje de tela (mt.)')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='listaprecios.lineaproducto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Producto',
                'db_table': 'listaprecios_variante_producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrecioVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio fijado manualmente')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios_variante', to='listaprecios.grupotela')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='listaprecios.varianteproducto')),
            ],
            options={
                'verbose_name': 'Precio de Variante',
                'verbose_name_plural': 'Precios de Variante',
                'db_table': 'listaprecios_precio_variante',
                'ordering': ['grupo__orden'],
            },
        ),
        migrations.CreateModel(
            name='PrecioGrupoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_metro', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio por metro')),
                ('rango_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rango mínimo')),
                ('rango_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rango máximo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_grupo', to='listaprecios.categorialista')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_categoria', to='listaprecios.grupotela')),
            ],
            options={
                'verbose_name': 'Precio de Grupo por Categoría',
                'verbose_name_plural': 'Precios de Grupo por Categoría',
                'db_table': 'listaprecios_precio_grupo_categoria',
                'ordering': ['categoria__orden', 'grupo__orden'],
            },
        ),
        migrations.CreateModel(
            name='CargoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='listaprecios.varianteproducto')),
            ],
            options={
                'verbose_name': 'Cargo de Variante',
                'verbose_name_plural': 'Cargos de Variante',
                'db_table': 'listaprecios_cargo_variante',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='preciovariante',
            constraint=models.UniqueConstraint(fields=('variante', 'grupo'), name='unique_variante_grupo'),
        ),
        migrations.AddConstraint(
            model_name='preciogrupocategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'grupo'), name='unique_categoria_grupo'),
        ),
    ]
