# Generated by Django 4.2.30 on 2026-08-24 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaprecios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineaproducto',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Línea de Producto', 'verbose_name_plural': 'Líneas de Producto'},
        ),
        migrations.RemoveField(
            model_name='categorialista',
            name='multiplicador_feria',
        ),
        migrations.RemoveField(
            model_name='categorialista',
            name='tiene_canal_feria',
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='listaprecios.categorialista'),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='notas',
            field=models.TextField(blank=True, default='', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='lineaproducto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='listaprecios.categorialista'),
        ),
    ]
