# Generated by Django 4.2.30 on 2026-08-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaprecios', '0003_paso2_quitar_categoria_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargovariante',
            name='opcional',
            field=models.BooleanField(default=False, verbose_name='Opcional (seleccionable al cotizar)'),
        ),
    ]
