# Generated by Django 4.2.30 on 2026-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaprecios', '0004_cargo_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianteproducto',
            name='multiplicador_modo',
            field=models.CharField(choices=[('categoria', 'Multiplicador general de la categoría'), ('ninguno', 'Sin multiplicador (precio = costo)'), ('personalizado', 'Multiplicador personalizado')], default='categoria', max_length=20, verbose_name='Modo de multiplicador'),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='multiplicador_personalizado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Multiplicador personalizado'),
        ),
    ]
