# Generated by Django 4.2.30 on 2026-08-26 16:53

from django.db import migrations, models
import django.db.models.deletion


def crear_multiplicador_general(apps, schema_editor):
    """Todas las categorías tenían multiplicador=1.76 antes de este cambio
    (confirmado en la sesión que hizo esta migración) — se preserva ese
    valor como el multiplicador "General" del nuevo catálogo, marcado por
    defecto. Las variantes no necesitan tocarse: su FK queda en NULL, que
    ya significa "usar el general"."""
    Multiplicador = apps.get_model('listaprecios', 'Multiplicador')
    Multiplicador.objects.get_or_create(
        nombre='General', defaults={'valor': '1.760', 'es_general': True, 'orden': 0},
    )


def eliminar_multiplicador_general(apps, schema_editor):
    Multiplicador = apps.get_model('listaprecios', 'Multiplicador')
    Multiplicador.objects.filter(nombre='General', es_general=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listaprecios', '0005_variante_multiplicador_personalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Valor')),
                ('es_general', models.BooleanField(default=False, verbose_name='Es el multiplicador general (por defecto)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Multiplicador',
                'verbose_name_plural': 'Multiplicadores',
                'db_table': 'listaprecios_multiplicador',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='categorialista',
            name='multiplicador',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='multiplicador_modo',
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='multiplicador_personalizado',
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='multiplicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variantes', to='listaprecios.multiplicador', verbose_name='Multiplicador (vacío = usar el general)'),
        ),
        migrations.RunPython(crear_multiplicador_general, eliminar_multiplicador_general),
    ]
