# Generated by Django 4.2.30 on 2026-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaprecios', '0006_multiplicador_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupotela',
            name='tipo',
            field=models.CharField(choices=[('tela', 'Tela'), ('cuero', 'Cuero')], default='tela', max_length=10, verbose_name='Tipo de material'),
        ),
    ]
