# Generated by Django 5.0.6 on 2026-03-28 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0010_add_direccion_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_manual', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('atrasada', 'Atrasada')], default='pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_suministros', to='ordenes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='suministros.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_suministros', to='ordenes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_referencia', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('variacion', models.CharField(blank=True, max_length=255)),
                ('costo_especifico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.CharField(choices=[('cliente', 'Cliente'), ('exhibicion', 'Exhibición'), ('consignacion', 'Consignación'), ('no_venta', 'No Venta'), ('venta', 'Venta')], default='cliente', max_length=50)),
                ('factura_manual', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.now)),
                ('imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='ordenes.ordenpedido')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='ordenes.venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario', to='suministros.producto')),
            ],
        ),
        migrations.CreateModel(
            name='RemisionSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('hora_desde', models.TimeField(blank=True, null=True)),
                ('hora_hasta', models.TimeField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('despachada', 'Despachada'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada'), ('devuelta', 'Devuelta')], default='creada', max_length=50)),
                ('sin_saldo', models.BooleanField(default=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, max_length=100)),
                ('transportador', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('inventario_items', models.ManyToManyField(blank=True, related_name='remisiones_suministros', to='suministros.inventario')),
                ('orden_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_suministros', to='ordenes.ordenpedido')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_suministros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='suministros.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.subcategoria'),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion', models.CharField(blank=True, max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='suministros.facturaproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suministros.producto')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.subcategoria')),
            ],
        ),
    ]
