# Generated by Django 5.0.6 on 2026-03-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='disponibilidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='venta_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
