# Generated by Django 5.0.6 on 2026-03-28 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_add_direccion_entrega'),
        ('suministros', '0002_detallefactura_disponibilidad_detallefactura_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.categoria'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.referencia'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.categoria'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_inventario_sum', to='ordenes.referencia'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
