# Generated by Django 5.0.6 on 2026-03-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0003_remove_inventario_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='detalle_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='suministros.detallefactura'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='suministros.facturaproveedor'),
        ),
    ]
