# Generated by Django 5.0.6 on 2026-04-01 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0004_inventario_detalle_factura_inventario_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='fecha_factura',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
