# Generated by Django 5.0.6 on 2026-04-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_rolepermission'),
        ('suministros', '0005_alter_facturaproveedor_fecha_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remisionsuministro',
            name='orden_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_suministros', to='ordenes.venta'),
        ),
    ]
