# Generated by Django 5.0.6 on 2026-04-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0006_alter_remisionsuministro_orden_asociada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='disponibilidad',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('exhibicion', 'Exhibición'), ('consignacion', 'Consignación'), ('por_despachar', 'Por Despachar'), ('no_venta', 'No Venta'), ('venta', 'Venta')], default='cliente', max_length=50),
        ),
    ]
