# Generated by Django 5.0.6 on 2026-04-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0007_alter_inventario_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisionsuministro',
            name='costo_entrega',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='remisionsuministro',
            name='nota_transportador',
            field=models.TextField(blank=True, null=True),
        ),
    ]
