# Generated by Django 5.0.6 on 2026-04-08 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0008_remisionsuministro_costo_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remisionsuministro',
            name='transportador_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_transportadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
