# Generated by Django 5.0.6 on 2026-04-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0009_remisionsuministro_transportador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisionsuministro',
            name='barrio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
