# Generated by Django 5.0.6 on 2026-04-18 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_rolepermission'),
        ('suministros', '0010_remisionsuministro_barrio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='suministros.grupoinventario'),
        ),
        migrations.CreateModel(
            name='GrupoInventarioComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.categoria')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='suministros.grupoinventario')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.referencia')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.subcategoria')),
            ],
        ),
    ]
