# Generated by Django 5.0.6 on 2026-05-31 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0011_grupoinventario_inventario_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinventario',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grupoinventario',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.subcategoria'),
        ),
    ]
