# Generated by Django 5.0.6 on 2026-05-31 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_remove_referencia_categoria_referencia_categorias_and_more'),
        ('suministros', '0012_grupoinventario_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_inventario', to='ordenes.venta'),
        ),
    ]
