# Generated by Django 5.0.6 on 2026-05-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0013_grupoinventario_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinventario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.categoria'),
        ),
    ]
