# Generated by Django 4.2.30 on 2026-07-15 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0014_grupoinventario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='fecha_factura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
