# Generated by Django 4.2.30 on 2026-07-16 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suministros', '0015_alter_facturaproveedor_fecha_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='estado_fisico',
            field=models.CharField(blank=True, default='nuevo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estado_fisico',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('exhibicion', 'De Exhibición'), ('averiado', 'Averiado'), ('garantia', 'En Garantía')], default='nuevo', max_length=50),
        ),
        migrations.AddField(
            model_name='inventario',
            name='qr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='suministros.sede')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('item_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_traslados', to='suministros.inventario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zona_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_destino', to='suministros.zona')),
                ('zona_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_origen', to='suministros.zona')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suministros.zona'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_inventario', to='suministros.zona'),
        ),
    ]
