# Generated by Django 4.2.30 on 2026-07-16 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0016_sede_detallefactura_estado_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='qr_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
