# Generated by Django 4.2.30 on 2026-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0017_alter_inventario_qr_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='disponibilidad',
            field=models.CharField(choices=[('exhibicion', 'Exhibición'), ('cliente', 'Cliente'), ('por_despachar', 'Por Despachar'), ('por_reparar', 'Por Reparar'), ('consignacion', 'Consignación'), ('no_venta', 'No a la venta')], default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado_fisico',
            field=models.CharField(choices=[('buen_estado', 'Buen estado'), ('por_reparar', 'Por reparar'), ('por_modificar', 'Por modificar')], default='buen_estado', max_length=50),
        ),
    ]
