# Generated by Django 4.2.30 on 2026-07-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0018_alter_inventario_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='disponibilidad',
            field=models.CharField(choices=[('exhibicion', 'Exhibición'), ('cliente', 'Cliente'), ('por_despachar', 'Por Despachar'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('por_reparar', 'Por Reparar'), ('consignacion', 'Consignación'), ('no_venta', 'No a la venta')], default='cliente', max_length=50),
        ),
    ]
