# Generated by Django 4.2.30 on 2026-08-03 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0022_iteminventariotelacuero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminventariotelacuero',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('atrasada', 'Atrasada')], db_index=True, default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='fecha_factura',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grupoinventario',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='historialtraslado',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='disponibilidad',
            field=models.CharField(choices=[('exhibicion', 'Exhibición'), ('cliente', 'Cliente'), ('por_despachar', 'Por Despachar'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('por_reparar', 'Por Reparar'), ('consignacion', 'Consignación'), ('no_venta', 'No a la venta')], db_index=True, default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='remisionsuministro',
            name='estado',
            field=models.CharField(choices=[('creada', 'Creada'), ('despachada', 'Despachada'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada'), ('devuelta', 'Devuelta')], db_index=True, default='creada', max_length=50),
        ),
        migrations.AlterField(
            model_name='remisionsuministro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
