# Generated by Django 4.2.30 on 2026-08-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0026_comprobanteegreso_recibido_por'),
        ('suministros', '0023_alter_iteminventariotelacuero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='comprobante_egreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ordenes.comprobanteegreso'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('atrasada', 'Atrasada'), ('pago_en_proceso', 'Pago en proceso')], db_index=True, default='pendiente', max_length=50),
        ),
    ]
