# Generated by Django 4.2.30 on 2026-08-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0024_facturaproveedor_comprobante_egreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='id_manual',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='facturaproveedor',
            constraint=models.UniqueConstraint(fields=('id_manual', 'proveedor'), name='unique_id_manual_por_proveedor'),
        ),
    ]
