# Generated by Django 4.2.30 on 2026-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0025_alter_facturaproveedor_id_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='estado',
            field=models.CharField(choices=[('pagada', 'Pagada'), ('pendiente', 'Pendiente'), ('atrasada', 'Atrasada'), ('pago_en_proceso', 'Pago en proceso'), ('anulada', 'Anulada')], db_index=True, default='pendiente', max_length=50),
        ),
    ]
