# Generated by Django 4.2.30 on 2026-09-26 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copiar_orden_asociada_a_ventas(apps, schema_editor):
    """Las remisiones existentes tenían una sola venta en `orden_asociada`; se copia al
    nuevo M2M `ventas` para que todo el histórico quede consistente."""
    RemisionSuministro = apps.get_model('suministros', 'RemisionSuministro')
    Through = RemisionSuministro.ventas.through
    filas = [
        Through(remisionsuministro_id=r_id, venta_id=v_id)
        for r_id, v_id in RemisionSuministro.objects.filter(orden_asociada__isnull=False)
        .values_list('id', 'orden_asociada_id')
    ]
    Through.objects.bulk_create(filas, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0035_alter_pagorecibocaja_estado'),
        ('suministros', '0026_alter_facturaproveedor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisionsuministro',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='remisionsuministro',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='remisionsuministro',
            name='cliente_telefono1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='remisionsuministro',
            name='cliente_telefono2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='remisionsuministro',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remisiones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remisionsuministro',
            name='ventas',
            field=models.ManyToManyField(blank=True, related_name='remisiones_suministros_multi', to='ordenes.venta'),
        ),
        migrations.CreateModel(
            name='RemisionItemManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observacion', models.TextField(blank=True)),
                ('detalle_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_remision_manuales', to='ordenes.detallepedido')),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_manuales', to='suministros.remisionsuministro')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_remision_manuales', to='ordenes.venta')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(copiar_orden_asociada_a_ventas, migrations.RunPython.noop),
    ]
