# Generated by Django 4.2.30 on 2026-09-26 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def asignar_permisos_remisiones(apps, schema_editor):
    """Reparte los permisos nuevos de Remisiones de forma que cada rol conserve lo que
    ya podía hacer antes de este cambio (luego se ajustan en Gestión de Usuarios):
      - quien tenía acceso y no es vendedor/transportador seguía viendo todas las remisiones;
      - quien podía crear y ve ventas de todos (misma regla del antiguo selector de O.C.)
        podía remisionar cualquier venta;
      - crear remisiones permitía modificarlas vía API (ahora: editar/estado/anular);
      - el costo del flete se veía en el listado para todos menos (ahora) vendedores;
      - reimprimir no existía: se habilita a quien tiene acceso al módulo.
    Los vendedores quedan viendo y remisionando solo sus ventas propias o compartidas."""
    RolePermission = apps.get_model('ordenes', 'RolePermission')
    for rp in RolePermission.objects.all():
        actuales = list(rp.permissions or [])
        s = set(actuales)
        if rp.role == 'administrador' or 'ALL' in s:
            continue
        ver = 'VER_REMISIONES' in s
        crear = 'CREAR_REMISION' in s
        ve_todas_ventas = bool(s & {'VER_TODAS_VENTAS', 'VER_TODAS_ORDENES', 'CREAR_ORDENES_OTROS'})
        es_vendedor = rp.role == 'vendedor'

        nuevos = set()
        if ver:
            nuevos.add('DESCARGAR_REMISION')
            if rp.role not in ('vendedor', 'transportador'):
                nuevos.update({'VER_TODAS_REMISIONES', 'VER_COSTO_ENTREGA_REMISION'})
            if rp.role == 'auxiliar':
                nuevos.add('CAMBIAR_ESTADO_REMISION')  # el modal anterior le dejaba cambiar el estado
        if crear:
            nuevos.add('EDITAR_REMISION')
            if not es_vendedor:
                nuevos.update({'CAMBIAR_ESTADO_REMISION', 'ANULAR_REMISION'})
                if ve_todas_ventas:
                    nuevos.add('CREAR_REMISION_TODAS_VENTAS')

        faltantes = [p for p in sorted(nuevos) if p not in s]
        if faltantes:
            rp.permissions = actuales + faltantes
            rp.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0035_alter_pagorecibocaja_estado'),
        ('suministros', '0027_remision_multiventa_items_manuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemisionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creada', 'Creada'), ('editada', 'Editada'), ('despachada', 'Despachada'), ('finalizada', 'Entregada'), ('devuelta', 'Devuelta'), ('anulada', 'Anulada'), ('reprogramada', 'Devuelta a programada')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('remision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='suministros.remisionsuministro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_remision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.RunPython(asignar_permisos_remisiones, migrations.RunPython.noop),
    ]
