# Generated by Django 4.2.30 on 2026-09-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suministros', '0028_remision_eventos_y_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisionsuministro',
            name='novedades',
            field=models.TextField(blank=True, default=''),
        ),
    ]
