# Generated by Django 4.2.30 on 2026-08-06 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorPerfil',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=False, verbose_name='Visible en la página web')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('cargo', models.CharField(blank=True, default='Asesor Comercial', max_length=120, verbose_name='Cargo')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('foto', models.CharField(blank=True, default='', max_length=500, verbose_name='Foto')),
                ('bio_corta', models.CharField(blank=True, default='', max_length=280, verbose_name='Bio corta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Perfil de Asesor',
                'verbose_name_plural': 'Perfiles de Asesores',
                'db_table': 'paginaweb_asesor_perfil',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
