# Generated by Django 4.2.30 on 2026-08-18 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0002_asesorperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PqrsTicket',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], default='peticion', max_length=20, verbose_name='Tipo de PQRS')),
                ('asunto', models.CharField(blank=True, default='', max_length=150, verbose_name='Asunto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_proceso', 'En proceso'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='recibido', max_length=20, verbose_name='Estado')),
                ('respuestas', models.JSONField(blank=True, default=list, verbose_name='Respuestas')),
                ('respondido_por', models.CharField(blank=True, default='', max_length=150, verbose_name='Respondido por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Ticket PQRS',
                'verbose_name_plural': 'Tickets PQRS',
                'db_table': 'paginaweb_pqrs_ticket',
                'ordering': ['-created_at'],
            },
        ),
    ]
