# Generated by Django 5.0.6 on 2025-10-18 20:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('cedula', models.CharField(db_index=True, max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='N/A', max_length=255, unique=True)),
                ('nombre_contacto', models.CharField(default='N/A', max_length=255)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(default='N/A', max_length=255)),
                ('ciudad', models.CharField(default='N/A', max_length=100)),
                ('telefono', models.CharField(default='0', max_length=20)),
                ('correo', models.EmailField(default='na@na.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador')], default='vendedor', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('concepto', models.CharField(default='', max_length=255)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('cierre', 'Cierre')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_acumulado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='ordenes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_index=True)),
                ('fecha_esperada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('recibido', 'Recibido'), ('anulado', 'Anulado')], db_index=True, default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('tela', models.CharField(blank=True, max_length=255, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orden_venta', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='ordenes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteEgreso',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], db_index=True, max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='ordenes.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('especificaciones', models.TextField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.ordenpedido')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.referencia')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('anulada', 'Anulada')], db_index=True, default='pendiente', max_length=20)),
                ('estado_pedidos', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ordenes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remisiones', to='ordenes.venta')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboCaja',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Davivienda', 'Davivienda'), ('Bancolombia', 'Bancolombia'), ('Bold', 'Bold'), ('Datafono Lottus', 'Datafono Lottus'), ('Otro', 'Otro')], db_index=True, max_length=50)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado')], db_index=True, default='Pendiente', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='ordenes.venta')),
            ],
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pedido', to='ordenes.venta'),
        ),
        migrations.CreateModel(
            name='ObservacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='ordenes.venta')),
            ],
        ),
    ]
