# Generated by Django 5.1.4 on 2025-01-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='especificaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordenpedido'),
        ),
    ]
