# Generated by Django 5.1.4 on 2025-03-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('AUXILIAR', 'Auxiliar'), ('VENDEDOR', 'Vendedor'), ('ADMINISTRADOR', 'Administrador')], default='AUXILIAR', max_length=15),
        ),
    ]
