# Generated by Django 5.0.6 on 2025-10-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteegreso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),

    ]
