# Generated by Django 5.0.6 on 2025-10-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_rename_nota_comprobanteegreso_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteegreso',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
