# Generated by Django 5.1.4 on 2025-01-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_detallepedido_especificaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.ordenpedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.referencia'),
        ),
    ]
