# Generated by Django 5.0.6 on 2025-07-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_caja_fecha_hora_alter_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(default='na@na.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(default='N/A', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
