# Generated by Django 5.1.4 on 2025-04-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='tela',
            field=models.CharField(choices=[('Por pedir', 'Por pedir'), ('Sin tela', 'Sin tela'), ('Por llegar', 'Por llegar'), ('En fabrica', 'En fabrica'), ('En Lottus', 'En Lottus')], default='Por pedir', max_length=20),
        ),
    ]
