# Generated by Django 5.0.6 on 2025-10-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_comprobanteegreso_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobanteegreso',
            name='nota',
        ),
    ]
