# Generated by Django 5.1.4 on 2025-01-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_detallepedido_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='orden_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
