# Generated by Django 5.0.6 on 2025-10-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_remove_comprobanteegreso_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre_contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='descripcion',
        ),
    ]
