# Generated by Django 5.0.6 on 2025-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_remove_proveedor_ciudad_remove_proveedor_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_encargado',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador'), ('auxiliar', 'Auxiliar')], default='vendedor', max_length=20),
        ),
    ]
