# Generated by Django 5.0.6 on 2025-12-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_proveedor_contacto_proveedor_nombre_encargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='confirmacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
