# Generated by Django 5.0.6 on 2026-02-16 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_recibocaja_confirmacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='N/A', max_length=255, unique=True)),
                ('nombre_encargado', models.CharField(default='N/A', max_length=255)),
                ('contacto', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoTela',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('direccion_entrega', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_index=True)),
                ('estado', models.CharField(choices=[('En fabrica', 'En fabrica'), ('En Lottus', 'En Lottus'), ('Pendiente', 'Pendiente')], db_index=True, default='Pendiente', max_length=20)),
                ('orden_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_telas', to='ordenes.ordenpedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_telas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='ordenes.proveedortela')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedidoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tela', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.pedidotela')),
            ],
        ),
    ]
