# Generated by Django 5.0.6 on 2026-03-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_proveedortela_pedidotela_detallepedidotela'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='requiere_tela',
            field=models.BooleanField(default=False),
        ),
    ]
