# Generated by Django 5.0.6 on 2026-03-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_add_requiere_tela_to_ordenpedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
            ],
        ),
    ]
