# Generated by Django 5.0.6 on 2026-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_add_direccion_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador'), ('auxiliar', 'Auxiliar'), ('transportador', 'Transportador')], default='vendedor', max_length=20),
        ),
    ]
