# Generated by Django 5.0.6 on 2026-04-08 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_alter_customuser_role'),
        ('suministros', '0005_alter_facturaproveedor_fecha_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='suministros.categoria'),
        ),
    ]
