# Generated by Django 5.0.6 on 2026-04-08 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_add_categoria_to_referencia'),
        ('suministros', '0005_alter_facturaproveedor_fecha_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='suministros.subcategoria'),
        ),
    ]
