# Generated by Django 5.0.6 on 2026-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0013_add_subcategoria_to_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador'), ('auxiliar', 'Auxiliar'), ('transportador', 'Transportador')], max_length=20, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
