# Generated by Django 5.0.6 on 2026-05-20 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sede',
            field=models.CharField(choices=[('Lottus 1', 'Lottus 1'), ('Lottus 2', 'Lottus 2')], default='Lottus 1', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='traslado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedores_compartidos',
            field=models.ManyToManyField(blank=True, related_name='ventas_compartidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
