# Generated by Django 5.0.6 on 2026-05-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_venta_sede_venta_traslado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='subcategoria',
        ),
    ]
