# Generated by Django 5.0.6 on 2026-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_remove_referencia_subcategoria'),
        ('suministros', '0011_grupoinventario_inventario_grupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='categoria',
        ),
        migrations.AddField(
            model_name='referencia',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='referencias', to='suministros.categoria'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='subcategorias',
            field=models.ManyToManyField(blank=True, related_name='referencias', to='suministros.subcategoria'),
        ),
    ]
