# Generated by Django 4.2.30 on 2026-07-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_remove_referencia_categoria_referencia_categorias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='es_exhibicion',
            field=models.BooleanField(default=False),
        ),
    ]
