# Generated by Django 4.2.30 on 2026-07-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0018_add_es_exhibicion_to_orden_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
