# Generated by Django 4.2.30 on 2026-07-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_cliente_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteegreso',
            name='medio_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Otro', 'Otro')], db_index=True, max_length=20),
        ),
    ]
