# Generated by Django 4.2.30 on 2026-08-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0020_alter_comprobanteegreso_medio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado_pedidos',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='sede',
            field=models.CharField(choices=[('Lottus 1', 'Lottus 1'), ('Lottus 2', 'Lottus 2')], db_index=True, default='Lottus 1', max_length=20),
        ),
    ]
