# Generated by Django 4.2.30 on 2026-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0021_alter_venta_estado_pedidos_alter_venta_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='dias_pago',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
