# Generated by Django 4.2.30 on 2026-08-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_proveedor_dias_pago_proveedor_porcentaje_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteegreso',
            name='estado',
            field=models.CharField(default='Por Confirmar Pago', max_length=50),
        ),
    ]
