# Generated by Django 4.2.30 on 2026-08-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0023_comprobanteegreso_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.referencia'),
        ),
    ]
