# Generated by Django 4.2.30 on 2026-08-06 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0024_alter_detallepedido_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteegreso',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='remision',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
