# Generated by Django 4.2.30 on 2026-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0025_alter_comprobanteegreso_fecha_alter_recibocaja_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteegreso',
            name='recibido_por',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
