# Generated by Django 4.2.30 on 2026-08-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0026_comprobanteegreso_recibido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteegreso',
            name='proveedor_otro_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='comprobanteegreso',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.proveedor'),
        ),
    ]
