# Generated by Django 4.2.30 on 2026-08-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0027_comprobanteegreso_proveedor_otro_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='es_feria_hogar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_feria_hogar',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
