# Generated by Django 4.2.30 on 2026-08-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0028_ordenpedido_es_feria_hogar_venta_es_feria_hogar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='sede',
            field=models.CharField(blank=True, choices=[('Lottus 1', 'Lottus 1'), ('Lottus 2', 'Lottus 2')], db_index=True, default='Lottus 1', max_length=20, null=True),
        ),
    ]
