# Generated by Django 4.2.30 on 2026-08-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0029_alter_venta_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidotela',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
