# Generated by Django 4.2.30 on 2026-08-11 23:39 — hand-edited to preserve data:
# 1) create PagoReciboCaja, 2) copy each ReciboCaja's valor/metodo_pago/estado/
# confirmacion into a new PagoReciboCaja row, 3) only then drop those fields
# from ReciboCaja.

from django.db import migrations, models
import django.db.models.deletion


def copiar_pagos(apps, schema_editor):
    ReciboCaja = apps.get_model('ordenes', 'ReciboCaja')
    PagoReciboCaja = apps.get_model('ordenes', 'PagoReciboCaja')
    for recibo in ReciboCaja.objects.all():
        PagoReciboCaja.objects.create(
            recibo=recibo,
            metodo_pago=recibo.metodo_pago,
            valor=recibo.valor,
            estado=recibo.estado,
            confirmacion=recibo.confirmacion,
        )


def revertir_pagos(apps, schema_editor):
    # No-op: la reversa de RemoveField (AddField) ya restaura las columnas en
    # ReciboCaja, pero sin datos — no hay a dónde "devolver" el valor de forma
    # inequívoca si llegó a haber más de un PagoReciboCaja por recibo.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0030_pedidotela_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoReciboCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Davivienda', 'Davivienda'), ('Bancolombia', 'Bancolombia'), ('Bold', 'Bold'), ('Datafono Lottus', 'Datafono Lottus'), ('Otro', 'Otro')], db_index=True, max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado')], db_index=True, default='Pendiente', max_length=20)),
                ('confirmacion', models.TextField(blank=True, null=True)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ordenes.recibocaja')),
            ],
        ),
        migrations.RunPython(copiar_pagos, revertir_pagos),
        migrations.RemoveField(
            model_name='recibocaja',
            name='confirmacion',
        ),
        migrations.RemoveField(
            model_name='recibocaja',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='recibocaja',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='recibocaja',
            name='valor',
        ),
    ]
