# Generated by Django 4.2.30 on 2026-08-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_remove_recibocaja_confirmacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteegreso',
            name='otros_conceptos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
