# Generated by Django 4.2.30 on 2026-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0032_comprobanteegreso_otros_conceptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador'), ('auxiliar', 'Auxiliar'), ('transportador', 'Transportador'), ('marketing', 'Marketing')], default='vendedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador'), ('auxiliar', 'Auxiliar'), ('transportador', 'Transportador'), ('marketing', 'Marketing')], max_length=20, unique=True),
        ),
    ]
