# Generated by Django 4.2.30 on 2026-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0033_customuser_add_marketing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='imagen_feria_hogar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
