# Generated by Django 4.2.30 on 2026-09-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0034_ordenpedido_imagen_feria_hogar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorecibocaja',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Anulado', 'Anulado')], db_index=True, default='Pendiente', max_length=20),
        ),
    ]
